In [1]:
import numpy as np
import math

## Array Creation

In [2]:
# Create 1D array
a = np.array([1,2,3,4])

In [3]:
print(a)

[1 2 3 4]


In [9]:
# Get dimensions of the array
print(a.ndim)

4


In [7]:
# Create 2D array
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# Get length of each dimension of the array
print(b.shape)

(3, 3)


In [11]:
# Check type of items in the array
print(b.dtype)

int64


In [13]:
# Create array with initial values

# Initialize with zeroes
c = np.zeros((2,2))
print(c)

# Initialize with ones
d = np.ones((2,2))
print(d)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


In [15]:
# Generate array with random values
e = np.random.rand(2,3)
print(e)

[[0.49995014 0.43695652 0.76735626]
 [0.31450808 0.87588634 0.52109435]]


In [20]:
# Generate an array with sequence of numbers

# Create array with every alternate number in range [10,20) 
f = np.arange(10,20,2)
f

array([10, 12, 14, 16, 18])

In [21]:
# Generate an array with sequence of floats

# Total 10 numbers between [0,2] 
g = np.linspace(0,2,10)
g

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

## Array Operations

In [22]:
# Arithmetic operations

h = np.array([1,2,3,4])
i = np.array([5,6,7,8])

# Add & Subtract
print(h+i)
print(h-i)

# Multiply
print(h*i)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]


In [27]:
# Arithmetic manipulations

# Convert fahrenheit to celcius
fahrenheit = np.array([0, -10, -5, -15])
celcius = (fahrenheit - 31) *(5/9)
print(celcius)

# Boolean operators
print(celcius > -20)

# arithmetic operators
print(celcius % 2 == 0)

[-17.22222222 -22.77777778 -20.         -25.55555556]
[ True False False False]
[False False  True False]


In [28]:
# Matrix manipulations
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

# multiply values ('*' operator)
print(A*B)

# multiply matrix ('@' operator)
print(A@B)


[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [31]:
# Automatic upcasting

arr1 = np.array([1,2,3,4])
print(arr1.dtype)

arr2 = np.array([1.1, 2.2, 3.3, 4.4])
print(arr2.dtype)

# Add
arr3 = arr1+arr2
print(arr3.dtype)

int64
float64
float64


In [37]:
# Aggregation functions

print(arr3)
print("sum {}".format(arr3.sum()))
print("max {}".format(arr3.max()))
print("min {}".format(arr3.min()))
print("mean {}".format(arr3.mean()))

[2.1 4.2 6.3 8.4]
sum 21.0
max 8.4
min 2.1
mean 5.25


In [39]:
# Create 2D array ith initial values

# generate a 3x5 array with values between [1,15]
arr4 = np.arange(1,16,1).reshape(3,5)
print(arr4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
